"Useful link to more vimrc config tips https://dougblack.io/words/a-good-vimrc.html

set number		"numbers the lines
syntax enable		"enables syntax processing
colorscheme solarized	"easy on the eyes
set showcmd		"shows command in bottom bar
set wildmenu		"visual autocomplete for command menu
set showmatch		"highlight matching [{()}]


